### ISSUE TITLE
executeOnlyIf - runs execute command first before assert-equals

### ISSUE THREAD

**Issue by ejdmfederizo** [concordion/concordion#287]
I tried putting the executeonlyif command inside a div, but then it runs the execute command first before assert-equals command?

<pre><code>
&lt;div ext:executeOnlyIf="isConfigured()" class="example"&gt;
 &lt;span concordion:assert-equals="getText()"&gt;foo/span&gt;
 &lt;span concordion:execute="clickOkButton()"&gt;/span&gt;
&lt;/div&gt;
</pre></code>

**Comment by ejdmfederizo** [comment]
&lt;div ext:executeOnlyIf="isConfigured()" class="example"&gt;
&lt;span concordion:assert-equals="getText()"&gt;foo/span&gt;
&lt;span concordion:execute="clickOkButton()"&gt;/span&gt;
&lt;/div&gt;

**Comment by nigelcharman** [comment]
Thanks for reporting this. The issue has (hopefully) been fixed in concordion-executeonlyif-extension release 0.3.1.

**Comment by ejdmfederizo** [comment]
Hi Nigel,

I used v0.3.1, and the issue is still occurring.

Thanks,
Eroll

**Comment by nigelcharman** [comment]
Are you able to paste the full HTML and Java code that illustrate the failure?

**Comment by ejdmfederizo** [comment]
Fixed, closing the issue
